export const mydata = [
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
  {
    Service: 'Buy and Ship Auto',
    Item: 'Black Sedan 2016, Toyota',
    'Start Date': 'Yesterday, 12PM',
    'Est Date of Delivery': '12 Jan, 2023 12PM',
    Status: 'Assigning Agents',
    'Action Required': 50,
  },
];
